### ISSUE TITLE
Package doesnt seem to have AddFormatAlias /  AddLocale functions

### ISSUE THREAD

**Issue by sapshah** [liamylian/jsontime#5]
I am importing this library and i get an error that the functions are not part of the package;  I am seeing the code and it seems that it is there. Is it something that I am not doing right?

**Comment by liamylian** [comment]
Just fixed a versioning bug, please try: 

`go get github.com/liamylian/jsontime/v2`

or

`go mod edit -require=github.com/liamylian/jsontime/v2@v2.0.0`

**Comment by liamylian** [comment]
I close it for now. Feel free to reopen if you still have problems.
